### ISSUE TITLE
New Syntax for CLI?

### ISSUE THREAD

**Issue by SandyRodgers-2017** [comictagger/comictagger#678]
I've been trying to use the cli version of comictagger and I keep getting this error when trying to use this command. 
`comictagger -s -t cr -m "publisher: 'Quality Comics'" *.cbz
`
comictagger: error: argument -m/--metadata: invalid parse_metadata_from_string value: "publisher: 'Quality Comics'"
 I thought I must have been doing something wrong, but I pulled this example directly from the cli guide thinking that it would work, however it does not. I am on the latest build directly for github. Was something changed and not added to the guide. The GUI works, but cli does not.

**Comment by lordwelch** [comment]
If you are comfortable pip installing an application, I recommend using https://github.com/ajslater/comicbox it has a much more robust cli for manual updates. I'll probably figure out why it isn't working later today

**Comment by lordwelch** [comment]
I think you might be on an old version, I can't re-produce this on the latest git commit. Can you provide the log? It would be located at.
`%LOCALAPPDATA%\ComicTagger\logs` on windows
`~/Library/Logs/ComicTagger` on macOS
`~/.cache/ComicTagger/log` on Linux

**Comment by SandyRodgers-2017** [comment]
Here is the log for when i used cli. It doesn't have much in it. Is there some way to make it more verbose? That right after I tried using command using cli.
[ComicTagger.log](https://github.com/user-attachments/files/16928769/ComicTagger.log)

and here is right after using gui, but not changing anything. 
[ComicTagger.log](https://github.com/user-attachments/files/16928794/ComicTagger.log)

**Comment by lordwelch** [comment]
Can you try running the appimage from the [release page]? I can't get it to fail in the same way

[release page]: https://github.com/comictagger/comictagger/releases/tag/1.6.0-alpha.22

**Comment by SandyRodgers-2017** [comment]
my version of glibc is too old for the appimage. It is part of the reason that I encode comictagger from source. I am on 2.31 but the appimage wants 2.35. Here is the error. I have python 3.9 installed though. 
[PYI-533785:ERROR] Failed to load Python shared library '/tmp/.mount_ComicTyKTDVx/_internal/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_ComicTyKTDVx/_internal/libpython3.9.so.1.0)

**Comment by lordwelch** [comment]
ok, lets try a virtual environment. Install pipx and run 
`pipx install git+https://github.com/comictagger/comictagger`
it will install comictagger in ~/.local/bin
This will install the latest development code. I pushed a commit to hopefully catch the error that happens properly

**Comment by lordwelch** [comment]
If you need some python packages (pyicu,qt5) installed by your package manager (apt,dnf,apk) you can use
`pipx install --system-site-packages git+https://github.com/comictagger/comictagger`

**Comment by SandyRodgers-2017** [comment]
I'll try that and report back. Thanks for the help.

**Comment by SandyRodgers-2017** [comment]
Tried it over the weekend still getting the same error message.  What should I post? The logs still haven't changed. The gui still works like it is supposed to. It's something going on with the cli. The cli was working for me before the syntax change around the time that I asked about a previous issue.

**Comment by lordwelch** [comment]
It should be impossible for it to produce the same message if you are using the current code. Please post the log

**Comment by DogInSpaace** [comment]
```
pipx install --system-site-packages git+https://github.com/comictagger/comictagger
```

I was also having a glibc error due to my system version being so old. This produced a fully functional binary for me. Thanks!

**Comment by lordwelch** [comment]
don't expect installing from git to ever work
